team-yello/YELLO-iOS

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Global/Resources/Color.swift
- YELLO-iOS/YELLO-iOS/Global/Resources/Font.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/AroundView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/AroundViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- 둘러보기 뷰 구현했습니다. 아직 완성되지 않은 이미지뷰는 추가하지 않았습니다!
- font, color 피그마에서 변화가 있어서 수정하였습니다.
- font에서 uiLabelBoldSmall이라는 폰트를 하나 추가했는데, 이 부분은 tabbar에서 선택된 아이템의 폰트입니다! 피그마에 따로 스타일이 명시되어 있지 않아서 따로 추가했습니다. 
| iPhone SE3 | ![Simulator Screenshot - iPhone SE (3rd generation) - 2023-07-07 at 00 09 24](https://github.com/team-yello/YELLO-iOS/assets/109775321/f7b16e16-c051-40ee-8543-75dba496ed99) |
Resolved #13
> Feat [#13] 둘러보기 뷰 UI 및 Font, Color 수정

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/KakaoFriendViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/RecommendingSegmentedControl.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/RecommendingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/SchoolFriendViewController.swift
- 추천친구 뷰에 있는 SegmentedControl를 구현했습니다. 아래에 뷰컨이 스와이프 시 바뀌도록 했습니다. 
- statusbar를 기준으로 top 위치를 잡을 때 사용한 코드입니다. trouble shooting에도 적어놨습니다! statusBar의 height를 구하고 그에 맞춰서 레이아웃을 잡을 때 중요한 부분일 것 같습니다.
```swift
recommendingLabel.snp.makeConstraints {
let statusBarHeight = UIApplication.shared.connectedScenes
.compactMap { $0 as? UIWindowScene }
.first?
.statusBarManager?
.statusBarFrame.height ?? 20
$0.top.equalTo(view.safeAreaInsets).offset(statusBarHeight + 22.adjusted)
$0.leading.equalToSuperview().offset(16.adjusted)
}
```
https://yell0.notion.site/top-b64cfd88d4bb4542ac6cbc6df4c8c1e5?pvs=4
| iPhone SE3 | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-07-07 at 01 31 …
> Feat [#15] 추천친구 뷰 SegmentedControl 구현

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift
- YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderField.swift
- KeychainHandler 추가 (SPM 설치도 했어용)
- HTTPHeaderField에 토큰 case 추가
- 없음
| 화면종류 | 없음 |
Resolved #62
> Network [#62] 추가 네트워크 세팅

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
- YELLO-iOS/YELLO-iOS/Network/Base/BaseResponse.swift
- YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/AddFriendsRequestQueryDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/KakaoLoginRequestDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/MajorSearchRequestQueryDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SchoolSearchRequestQueryDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SignInRequestDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/aa.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/CheckDuplicateResponeDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/KakaoLoginResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/MajorSearchResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/SchoolSearchResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/SignInResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/b.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
카카오 엑세스 토큰 서버에 보내주는 API를 연결했습니다. 
| 카카오톡로그인 | 없음 |
Resolved #65
> Network [#65]  카카오톡 연결

- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Global/Resources/Color.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/KakaoLoginResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Payment/PaymentReadyViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindMajorViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindSchoolViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/ProfileViewController.swift
- 아이디 중복 체크 API를 이용해서 아이디 중복 처리 기능을 구현했습니다. 
- 아이디를 `query`로 보내주면 다음과 같은 결과를 얻을 수 있습니다. 
> 중복된 아이디를 입력한 경우 
``` json
{
"status": 200,
"message": "조회 성공하였습니다.",
"data": true
}
```
> 중복되지 않은 아이디를 입력한 경우
```json
{
"status": 404,
"message": "존재하지 않는 유저입니다.",
"data": null	
}
```
`data`가 `Bool?` 타입(`null`값을 가질 수 있기 때문에 옵셔널 타입) `BaseResponse` 대신 `IdValidResponseDTO` DTO를 따로 만들어서 사용했습니다. 
``` swift
// MARK: - IDValidResponseDTO
struct IDValidResponseDTO: Codable {
let status: Int
let message: String
let data: Bool?
}
```
- `data`값이 `nil`인 경우가 있기 때문에 `data.data`를 옵셔널 언래핑을 할 때 `return` 을 하게되면 아이디 중복 검사를 제대로 할 수 없습니다. 언래핑 코드를 없애고 다음과 같이 사용했습니다. 
https://github.com/team-yello/YELLO-iOS/blob/f85c6237999ea58977f3ee283ae1a5c9b65c88a3/YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoView …
> Network [#77] 아이디 중복 체크 API 연결 및 로직 처리 

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
- YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift
- YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
- InvitingView 카카오톡 친구초대 구현
- 아래와 같이 친구초대 버튼을 클릭할 시 카카오톡으로 추천인코드와 함께 메세지를 보낼 수 있습니다 ‼️
https://github.com/team-yello/YELLO-iOS/blob/61307f5054c404cac391980fa5dc3ce6d1cab9c3/YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift#L169-L196
- 메세지 템플릿에서 아래와 같은 형식으로 헤더에 ${KEY}를 넣어주고 서버를 불러올 때 KEY 값에 추천인코드를 넣어주면 됩니당 !
| 카카오톡 친구초대 메세지 | ![IMG_1911](https://github.com/team-yello/YELLO-iOS/assets/97782228/a8c76190-cac7-4bd2-8c5b-536f64c6ae11) |
Resolved #84
> Feat [#84] 카카오톡 친구초대 구현

- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- TabBar 서버통신 viewWillAppear -> viewDidLoad로 옮김
- TabBar selectedIndex 2일 때 서버통신 다시하도록 수정
- 이제 정상적으로 작동합니당 🫠
Resolved #96
> Chore [#96] TabBar 서버통신 로직 수정

- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
- `UserDefault`에  로그인 여부를 확인하는 변수 `isLoggined`를 통해서 `rootViewController` 분기 처리를 합니다. 
- 처음에 `UserDefault`를 SceneDelegate에서 초기화를 합니다. 이 때, 초기값은 false입니다. 
https://github.com/team-yello/YELLO-iOS/blob/b0defb4812f8ee979f2000a92d64960e5c14ff08/YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift#L15
- `isLoggined`로 분기처리를 하여 rootViewController를 설정합니다. 
https://github.com/team-yello/YELLO-iOS/blob/b0defb4812f8ee979f2000a92d64960e5c14ff08/YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift#L29-L31
- 로그아웃 / 회원 탈퇴 시 `isLoggined`의 값을 지웁니다. 
https://github.com/team-yello/YELLO-iOS/blob/b0defb4812f8ee979f2000a92d64960e5c14ff08/YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift#L62-L68
| 로그인  | …
> Fix [#97] 자동 로그인 구현

- YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindMajorViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/FindSchoolViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift
- 임의로 구글로 설정했던 링크들 기획에게 실제 링크 받아서 수정했습니다.
- 없습니다.
| 화면종류 | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-07-20 at 18 33 08](https://github.com/team-yello/YELLO-iOS/assets/109775321/b975237c-f671-4f15-b1d3-31826b748841)  |
온보딩 부분은 확인이 힘들어서 확인은 못했는데 링크 바꿔서 다른 버튼에 심어두고 확인 했습니다!
Resolved #106
> Feat [#106] 실제 링크 연결

- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
- 스크롤 터지는 이슈
- 키워드 헤드에 따른 띄어쓰기 분기처리
- 없음
| 화면종류 | 없음 |
Resolved #100
> Fix [#100] 내 옐로 스크롤 및 띄어쓰기 이슈

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift
- YELLO-iOS/YELLO-iOS/Network/Base/MyRequestInterceptor.swift
- YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/TokenRefreshResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift
토큰 재발급 로직을 수정했습니다. 
| 토큰 로직 수정 | 없습니다. |
Resolved #117
> Fix [#117] 토큰 재발급 로직 수정

- README.md
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
- VotingStartViewController에서 getVotingList()하기 전까지 시작버튼 disable 처리
- yelloProgressBackGround 설정하는 코드 효율적으로 정리
- TabBar 초기 rootViewController을 VotingStartViewController로 수정
- keywordList 배열 append 부분을 count를 받아와서 적용
- 이제 투표시작화면에서 앱이 터지는 경우가 (아마도) 발생하지 않을 거에요 ,, !!
Resolved #121
> Fix [#121] 2차 스프린트 전 수정사항 반영

- YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift
- YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
- YELLO-iOS/YELLO-iOS/Network/Base/MyRequestInterceptor.swift
- YELLO-iOS/YELLO-iOS/Network/Base/NetworkResult.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Response/TokenRefreshResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
- refreshToken이 제대로 작동하지 않는 코드를 수정했습니다. 
interceptor의 retry가 실행이 되지 않아 status code에 대한 분기 처리로 따로 작성했습니다. 더 좋은 방법이 생각난다면 언제든 의견주세요!
| 토큰 재발급  | <img width="372" alt="image" src="https://github.com/team-yello/YELLO-iOS/assets/68178395/f5ae5bd1-86e7-4c5f-8dff-5d4875f7ce76"> |
Resolved #122
> Fix [#122] refresh token 로직 수정 완료

- YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingListResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Enum/BackgroundColor.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingData.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
- 앱을 껐다 켜도 원래 화면이 유지되게끔 SceneDelegate를 설정
- UserDefaults를 사용한 local DB 구현
- 데이터 전달, DTO 수정
⬇️ local DB를 사용하여 앱이 종료될 때 원래 화면을 저장해두고, 앱이 실행될 때 원래 화면을 다시 띄웁니다 ‼️
- 앱이 켜질 때 제일 처음 실행되는 scene 함수에 아래와 같이 코드를 추가했습니다. 
https://github.com/team-yello/YELLO-iOS/blob/bb585a2ced6bc8555d5e29cabf5b88aef0045213/YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift#L17-L51
- 앱이 강제종료될 때 실행되는 sceneDidDisconnect 함수에 아래와 같이 코드를 추가했습니다.
https://github.com/team-yello/YELLO-iOS/blob/bb585a2ced6bc8555d5e29cabf5b88aef0045213/YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift#L62-L69
- 앱이 백그라운드로 진입할 때 실행되는 sceneDidEnterBackground 함수에 아래와 같이 코드를 추가했습니다.
https://github.com/team-yello/YELLO-iOS/blob/bb585a2ced6bc8555d5e29cabf5b88aef0045213/YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift#L86-L94 …
> Feat [#125] SceneDelegate 설정 및 Loacl DB 구현

- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
- 투표 중복으로 보내지는 이슈 해결
- 투표를 보낼 때마다 Loacl DB에서 데이터를 삭제하도록 수정하였습니다.
https://github.com/team-yello/YELLO-iOS/blob/dc4571a67314ac51f93d4024b5446827053f75f0/YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift#L119-L135
Resolved #133
> Fix [#133] 투표 중복으로 보내지는 이슈 해결

- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/Cell/MyFriendSkeletonTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/Cell/MyFriendTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
- 내 옐로 첫번째 쪽지 구현했습니다..
- 구독 여부와 열람권 유무에 따라서 더 바뀔 것 같습니다..
| 화면종류 | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-08-14 at 01 09 42](https://github.com/team-yello/YELLO-iOS/assets/109775321/b6d96123-64db-4947-919d-4eeee3eb95cd) |
Resolved #169
> Feat [#169] 내 옐로 첫번째 쪽지 구현

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Network/Around/DTO/Request/AroundRequestDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Around/DTO/Response/AroundResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Around/Router/AroundTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Around/Service/AroundService.swift
- YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/Cell/AroundTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundEmptyView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Cells/FriendTableViewCell.swift
- 둘러보기 서버통신 했습니다
- 없습니다~
| 둘러보기  |  ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-08-14 at 22 55 46](https://github.com/team-yello/YELLO-iOS/assets/109775321/7a04ef1a-00de-40bb-9922-2f8ef4653ca1)|
Resolved #174
> Network [#174] 둘러보기 API 연결

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Network/Base/NetworkService.swift
- YELLO-iOS/YELLO-iOS/Network/Recommending/DTO/Response/RecommendingFriendResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Search/DTO/Request/FriendSearchRequestQueryDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Search/DTO/Response/FriendSearchResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Search/Router/SearchTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Search/Service/SearchService.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloOnlyNameTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/Cells/FriendSearchTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/View/FriendSearchView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
- 친구 검색 API 연결했습니다
- debounce 연결은.. 안하기로 서버랑 쇼부 봤습니다.
- 제가 헷갈려서 브랜치를 178로 팠습니다.. 177입니다.. 커밋도 178로 했습니다.. 희주에게 양해를 구합니닿..ㅋ
| 검색 | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-08-15 at 18 52 21](https://github.com/team-yello/YELLO-iOS/assets/109775321/965a81cd-d227-4540-bab6-b7117ddf4c44)|
Resolved #177
> Network [#177] 친구 검색 API 연결

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
- YELLO-iOS/YELLO-iOS/Info.plist
- YELLO-iOS/YELLO-iOS/Network/Base/Config.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ProgressBarManager.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/PaymentReadyViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/ViewController/KakaoFriendViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Tutorial/ViewController/TutorialViewController.swift
- Amplitude 기본 설정 및 연결을 완료했습니다. 
- 온보딩 부분 이벤트 연결을 마쳤습니다.
- [TIL](https://www.notion.so/go-sopt/9c40d4d50bbc482684d1454c231c7787?pvs=4)에 설명 적어뒀습니다! 
| 온보딩 |없습니다! |
Resolved #188
> Feat [#188] Amplitude 연결

- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Button/MyYelloButton.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloView.swift
- 내 옐로 버튼 스타일 바뀐 거 수정사항 반영했습니다
- 없습니다
|    구현 내용    |   내 옐로 메인   |  내 옐로 디테일 |
| :-------------: | :----------: |:----------: |
| 구독권 없을 때 | ![Simulator Screenshot - iPhone SE (3rd generation) - 2023-08-17 at 15 02 46](https://github.com/team-yello/YELLO-iOS/assets/109775321/2551e754-d9f9-4b13-b5d0-0e42607b0114) |  ![Simulator Screenshot - iPhone SE (3rd generation) - 2023-08-17 at 15 02 48](https://github.com/team-yello/YELLO-iOS/assets/109775321/af75ce58-af99-4cee-8b85-7c3ea32e6666) |
| 구독권 있을 때 | ![Simulator Screenshot - iPhone SE (3rd generation) - 2023-08-17 at 15 03 49](https://github.com/team-yello/YELLO-iOS/assets/109775321/caeae330-a0a4-4744-93c8-66d1ceebe01d) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2023-08-17 at 15 03 …
> Fix [#190] 내 옐로 수정사항 반영

- YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
- 아이콘 뱃지 로직 수정
- AppDelegate에 추가했던 함수를 삭제했습니다.
앱아이콘 실시간 업데이트
https://github.com/team-yello/YELLO-iOS/assets/97782228/16bb4b95-c0aa-42f5-819f-3a2b16a823fa
Resolved #193
> Fix [#193] 아이콘 뱃지 로직 수정

- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Global/Extensions/UILabel+.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UsePointView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloHelperLabel.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextFieldView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/UserInfoView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
온보딩의 디테일들을 추가하고 오류가 나는 앰플리튜드를 추가했습니다. 
없습니다. 
| 온보딩 | 없습니다.  |
Resolved #202
> Feat [#202] 온보딩 디테일 수정 및 앰플리튜드 이벤트 변경

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Response/PurchaseInfoResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
- 옐로 플러스 구독 여부에 따라 프로필과 옐로하기에서 UI가 바뀌도록 하는 부분 추가했습니다.
- 없습니다
|    옐로하기    |   내프로필   |
|  ![IMG_7544](https://github.com/team-yello/YELLO-iOS/assets/109775321/4da6fa4e-9a42-4cdb-b42b-4dfdb6f725b6) |  ![IMG_7543](https://github.com/team-yello/YELLO-iOS/assets/109775321/d3254db2-db0a-4f1d-a24e-1e22d3374c71) |
Resolved #205
> Network [#208] 옐로 플러스 구독 여부 UI 연결

- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/PushSettingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
서버에서 추가한 userproperty와 결제 관련 앰플리튜드를 추가했습니ㅏㄷ.
없습니다!
| 앰플리튜드 추가 | 없습니다! |
Resolved #217
> Fix [#217] Amplitude 추가

- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/Cells/FriendSearchTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/View/FriendSearchView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
- 검색 부분 재사용 이슈 생기는 부분들과 기타 버그 수정했습니다
- 없습니다.
| 화면종류 | 없습니다. |
Resolved #220
> Fix [#220] 검색 재사용 이슈 해결

- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
-  타이머 뷰에 포인트 실시간 업데이트 안되는 것 해결
-  타이머 넘어가기 전에 투표 대기뷰가 살짝 보이는 이슈 해결
-  상단 포인트 서버통신 지연시 "000"으로 표시
- 내용
투표 대기뷰가 살짝 보이는 이슈 해결
https://github.com/team-yello/YELLO-iOS/assets/97782228/96a9ad78-11ac-46e0-941b-76c1e68c8939
Resolved #222
> Feat [#222] QA 사항 반영

- YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Purchase/Router/PurchaseTarget.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
- 서버 라우트 변경 사항과 디자인 QA를 반영했습니ㅏ
- 서버 라우트 변경 - 결제 부분
- 디자인 QA - 아무것도 검색하지 않았을 때 아무 화면도 안뜨도록
- 친구 검색에서 서버 통신 느려지는 순간에 가끔 검색한 결과가 없어요가 뜨긴 하는데 .. ㄱㅊ을 거라고 생각합니다.. 이건 어케 할 수 있는 방법이 x
| 화면종류 | x |
Resolved #228
> Fix [#228] 서버 수정사항 및 디자인 QA 반영

- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- 상점의 products가 불러와지는 시점을 수정했습니다.
- 키워드 불일치 문제는 iOS 측 문제 아닌 걸로 확인되었습니다!
- 없습니다.
| 화면종류 | 없습니다. |
Resolved #236
> Fix [#236] 상점 로드 시점 수정

- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
- 외부 QA 사항을 반영했습니다. 
- 통신 횟수 제한
- 통신 오류 시 토스트 메시지
없습니다!
| 화면종류 | 없습니다. |
Resolved #237
> Fix [#237] 외부 QA 반영

- YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- 상점 구독 여부 시점이 viewDidLoad에 있어서 viewWillAppear로 수정했습니다.
- 불규칙적인 상황에서 아주 가끔 구독 결제 부분이 자동으로 불러와지는데 추후 확인이 필요할 것 같습니다.
| 화면종류 | x |
Resolved #243
> Fix [#243] 상점 구독 여부 시점 수정

- YELLO-iOS/YELLO-iOS/Network/Search/Router/SearchTarget.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/ViewController/FriendSearchViewController.swift
- 친구 검색에서 전체 이름 검색 / 첫 이름 검색 시 안뜨는 문제를 해결했습니다.
- 친구 검색에서 텍스트필드에 아무것도 남아있지 않을 때 뜨는 화면을 해결했습니다.
- 없습니다
https://github.com/team-yello/YELLO-iOS/assets/109775321/537833fb-bffb-47d2-b1c0-457eb8c29e34
Resolved #246
> Fix [#246] 친구 검색 QA 반영

- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UsePointView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UseTicketView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
[Amplitude QA](https://www.notion.so/yell0/Amplitude-QA-96d6f23355ed4812bd389ee510afa1fd?pvs=4) 사항을 반영했습니다. 
[Amplitude > User-LookUp](https://app.amplitude.com/analytics/yelloworld/activity)에서 QA 가능합니다.
user_name으로 필터링해서 보면 편하게 볼 수 있습니다!
| 전체적으로 수정 | 없습니다.  |
Resolved #249
> Fix [#249] Amplitude QA 사항 반영

- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Network/Voting/DTO/Response/VotingAvailableResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- 옐로하기_잠금 버튼 라이팅 변경
- 옐로하기_시작 친구 1~3명일 때 말풍선 추가
- 옐로하기_메인 친구 1~3명일 때 친구 없는 부분 "친구를 추가해주세요!" 라이팅으로 변경
- 옐로하기_메인 친구 1~3명일 때 친구 없는 부분 클릭시 토스트메세지 띄우기
- 셔플 버튼 클릭 시에도 친구 이름이 들어가 있는 부분만 셔플이 적용됩니다 ‼️
| 친구 1~3명인 경우 투표시작화면| ![Simulator Screen Recording - YELL O_TEST - 2023-09-13 at 15 28 40](https://github.com/team-yello/YELLO-iOS/assets/97782228/66fdc2df-3ce8-4dea-acec-92f0fd21e263) |
| 친구 1~3명인 경우 투표화면 | ![Simulator Screen Recording - YELL O_TEST - 2023-09-13 at 15 43 44](https://github.com/team-yello/YELLO-iOS/assets/97782228/aa1699f4-5f51-4ef8-9e05-08f15fbb680c) |
Resolved #252
> Feat [#252] 4명 이하 투표 뷰 수정사항 반영

- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Global/Shared/AppStoreCheck.swift
- 강제 업데이트 알럿이 띄워지지 않는 이슈 해결했습니다. 해당 url에 https가 아니라 http로 되어 있어서 되지 않았던 것 같습니다... 
- URL 관련 메인 스레드에서 실행하지 않도록 URLSession으로 바꿔주었습니다. 
- x
| 화면종류 | x |
Resolved #261
> Fix [#261] 강제 업데이트 안되는 이슈 해결

- YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift
- YELLO-iOS/YELLO-iOS/Network/Base/MyRequestInterceptor.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift
토큰이 만료되면 로그아웃되도록 수정했습니다. 
카카오 api에서 토큰이 만료되면 로그아웃이 안되는 에러를 발견했습니다.
| 토큰 로직 수정 | 없습니다 |
Resolved #270
> Fix [#270] 로그아웃 이슈 해결

- YELLO-iOS/YELLO-iOS/Global/Extensions/UIView+.swift
- YELLO-iOS/YELLO-iOS/Global/Literals/Image.swift
- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icSalePolygon.imageset/Contents.json
- YELLO-iOS/YELLO-iOS/Global/Resources/Assets.xcassets/icSalePolygon.imageset/icSalePolygon.svg
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloNavigationBarView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/Button/PaymentNameKeyButton.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/Button/PaymentYelloPlusButton.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentPlusView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift
- 유료 결제 금액 변경에 따른 UI를 수정했습니다. (내 옐로, 상점, 내 프로필)
- AppStoreConnect 금액 변경은 논의 후 심사와 함께 변경할 예정입니다.
|    상점   |   내 옐로   |   프로필   |
| :-------------: | :----------: | :----------: |
| ![Simulator Screen Recording - iPhone 15 - 2023-11-05 at 17 28 38](https://github.com/team-yello/YELLO-iOS/assets/109775321/d2073961-4e68-46a6-ac67-ba6c1a779e7e)    |  ![Simulator Screenshot - iPhone 15 - 2023-11-05 at 17 28 18](https://github.com/team-yello/YELLO-iOS/assets/109775321/08ee1c21-901b-43f3-9a95-b0d48bbf18c3)   |  ![Simulator Screenshot - iPhone 15 - 2023-11-05 at 17 28 43](https://github.com/team-yello/YELLO-iOS/assets/109775321/12ee386a-ab85-4f2a-88b6-0651952bcf9c)  |
Resolved #272
> Feat [#272] 유료결제 금액 변경에 따른 UI 수정

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Network/Around/DTO/Response/AroundResponseDTO.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/Cell/AroundSkeletonTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/Cell/TimeLineTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/Button/InstagramButton.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- 11월 업데이트건인 타임라인 tableViewCell Style과 인스타그램 공유 버튼 수정 사항을 반영했습니다.
- 내용
|    타임라인    |   인스타그램 공유 흰색   | 인스타그램 공유 검정색   |
| :-------------: | :----------: | :----------: |
| ![Simulator Screenshot - iPhone 15 - 2023-11-07 at 01 32 02](https://github.com/team-yello/YELLO-iOS/assets/109775321/cca5eca3-3f22-4925-aa44-da13593b7709)   |  ![Simulator Screenshot - iPhone 15 - 2023-11-07 at 01 32 10](https://github.com/team-yello/YELLO-iOS/assets/109775321/09dcd616-7ed6-45c1-bc18-9df68cb01bca)    | ![Simulator Screenshot - iPhone 15 - 2023-11-07 at 01 32 19](https://github.com/team-yello/YELLO-iOS/assets/109775321/89f53c6e-6049-4cbc-aad8-186d69ab55b6) |
Resolved #274
> Feat [#274] 타임라인 및 인스타그램 공유 버튼 수정

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- 플러스는 포인트 2배 위치
- 투표시작 버튼의 위치와 크기, 라이팅이 변경
- X
| 수정사항 | ![image](https://github.com/team-yello/YELLO-iOS/assets/97782228/601718d0-e965-42da-abf7-f1e9e8d629f5) |
Resolved #275
> Fix [#275] 옐로하기 뷰 수정사항 적용

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift
카카오 로그인 관련 버그 수정
카카오 SDK를 이용한 서버 통신 이후에는 메인쓰레드에서 다음 작업을 진행해야 합니다!
카카오 SDK 권장 버전으로 업데이트했습니다. 
| 카카오 로그인 | 없습니다 |
Resolved #282
> Fix [#282] 카카오로그인 버그 

- YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift
- YELLO-iOS/YELLO-iOS/Global/Literals/String.swift
- YELLO-iOS/YELLO-iOS/Global/Resources/Color.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/Button/InstagramButton.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- 인스타그램 공유하기 버튼 UI 수정사항을 반영했습니다.
- color 추가되어서 해당 사항 추가했습니다!
|    아무것도 안깠을 때    |    다 깠을 때   |    키워드 초성 깠을 때   |  이름만 깠을 때   |
| :-------------: | :----------: | :-------------: | :----------: |
|  ![IMG_4971](https://github.com/team-yello/YELLO-iOS/assets/109775321/4119e639-3ed3-4942-ab39-239d4a3ddc4e)       |    ![IMG_4972](https://github.com/team-yello/YELLO-iOS/assets/109775321/be2cd2f2-524d-42d7-9292-08532af94c39)    |    ![IMG_4973](https://github.com/team-yello/YELLO-iOS/assets/109775321/1d342c3b-187f-41e1-b68a-48aec02ed290)  |    ![IMG_4975](https://github.com/team-yello/YELLO-iOS/assets/109775321/06f97c7b-0b70-4eee-92ed-20a2a19380e3)    |
Resolved #294
> Feat [#294] 인스타그램 공유하기 UI 수정사항 반영

- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- 화면전환 시 화면에 필수적으로 머물러야하는 시간만큼 skip 버튼의 비활성화 시간도 추가하여 화면에 머물러야 하는 시간동안 skip 버튼이 활성화되지 못하도록 구현하였습니다.
- X
Resolved #299
> Fix [#299] 버튼 중복 클릭 시 애니메이션으로 인한 오류 방지

- YELLO-iOS/YELLO-iOS/Network/Around/Router/AroundTarget.swift
- YELLO-iOS/YELLO-iOS/Network/MyYello/Router/MyYelloTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Notification/Router/NotificationTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Purchase/Router/PurchaseTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Recommending/Router/RecommendingTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Search/Router/SearchTarget.swift
- YELLO-iOS/YELLO-iOS/Network/Voting/Router/VotingTarget.swift
- v2 API 나오면서 config 파일 뒤에 '/v1' 를 떼어내고 target에 있는 path에 /v1을 붙였습니다!
- config 랑 config_dev 파일에 /v1을 떼어내고 작업해주세요!
- 위와 같습니다
| 화면종류 | x |
Resolved #311
> Chore [#311] v1 v2 분리

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/TabBarHeight.swift
개발 최소 버전을 15.으로 변경했습니다. 
15.0 미만 버전을 처리하기 위한 `if #avaliable` 코드를 정리했습니다. 
나머지 PR에 있는 코드들은 머지 이후 정리해주시면 갑사하겠습니다!!
| 화면종류 | 없습니다! |
Resolved #308
> Chore [#308] 최소 버전 변경

- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
- 투표가 계속 안보내지는 문제를 해결했습니다 !
- 데이터를 저장하는 위치만 변경했습니다.
| 화면종류 | X |
Resolved #338
> Fix [#338] 옐로하기 수정

- YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
- 3차 스프린트 3차 QA 후 수정 사항 반영했습니다.
- 내 쪽지 레이아웃 깨지고 쪽지가 제대로 보여지지 않는 사항이 생겨서 해당 부분 수정하였습니다.
- x
| 화면종류 | ![Simulator Screen Recording - iPhone 15 - 2024-02-25 at 22 39 06](https://github.com/team-yello/YELLO-iOS/assets/109775321/03e2a59c-c73d-4452-a261-9bc838d332ca)   |
Resolved #343
> Fix [#343] 내 쪽지 레이아웃 깨지는 사항 수정

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift
- YELLO-iOS/YELLO-iOS/Global/Shared/UserManager.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/NameViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloTextField.swift
- YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/NameView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/AdsTimer/Timer.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/Search/View/FriendSearchView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
디자인 이슈들과 기능적 이슈 해결했습니다. 
내 옐로 광고 부분은 모든 PR 머지 후 광고에 대한 에러 처리 추가로 해야할 것 같습니다!
미디에이션 연결은 했으나, 실제 앱으로 연동되어야 정확한 확인이 가능할 것 같습니다. 앱 추적 금지 요청을 하면 일단 광고 없이 넘어가도록 처리해뒀으며, 미디에이션 그룹 연동 후에는 사용자와 연관없는 광고가 뜨도록 처리되어 있습니다. 
| 화면종류 | 없습니다 |
Resolved #342
> Fix [#342] 3차 스프린트 3차 QA 사항 반영

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
- 투표 안되는 이슈 해결
- 투표 키워드 뒤죽박죽 이슈 해결
- X
| 화면종류 | X |
Resolved #344
> Fix [#344]  옐로하기 이슈 해결

- YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/Button/PaymentNameKeyButton.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/Button/PointButton.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
출시 전 발생한 오류들을 수정했습니다. 
- 상점뷰 네비게이션바 열람권 개수 반영
- 열람권 버튼 터치 영역 
- 옐로 플러스일 때, 광고 2배 버튼 Hidden 처리
없습니다
| 화면종류 | 없습니다! |
Resolved #348
> Fix [#348] 출시 전 qa 사항 수정

- YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj
- YELLO-iOS/YELLO-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Around/ViewController/AroundViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditProfileViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
- 3차 스프린트 5차 QA 사항 반영했습니다 (타임라인에서 보낸 쪽지 없을 때 투표하기로 넘어감, 내 프로필 친구 empty 분기처리)
- 3차 스프린트 앰플리튜드 연결
- x
|   타임라인 보낸 쪽지 없을 때 투표하기로 이동 |  
| :-------------: | 
| ![Simulator Screen Recording - iPhone 15 - 2024-03-25 at 01 21 10](https://github.com/team-yello/YELLO-iOS/assets/109775321/2f2f0eeb-a9f9-474d-a077-d984c3846c27)  | 
Resolved #362
> Fix [#362] 3차 스프린트 5차 QA 수정사항 반영 및 앰플리튜드 반영

- YELLO-iOS/YELLO-iOS/Presentation/Event/ViewController/LunchEventViewController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift
- YELLO-iOS/YELLO-iOS/Presentation/Subscription/SubscriptionExtensionView.swift
- YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
- 옐로하기 뷰, 공지 팝업, 점심시간 이벤트, 재구독 뷰에 앰플리튜드를 심었습니다.
- X
| 화면종류 | X |
Resolved #364
> Feat [#364] 담당 뷰 앰플리튜드 적용
