YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Global/Extensions/adjust+.swift
- adjust extension 추가했습니다!
```swift
import UIKit
extension CGFloat {
var adjusted: CGFloat {
let ratio: CGFloat = UIScreen.main.bounds.width / 375
let ratioH: CGFloat = UIScreen.main.bounds.height / 667
return ratio <= ratioH ? self * ratio : self * ratioH
}
var adjustedWidth: CGFloat {
let ratio: CGFloat = UIScreen.main.bounds.width / 375
return CGFloat(self) * ratio
}
var adjustedHeight: CGFloat {
let ratio: CGFloat = UIScreen.main.bounds.height / 667
return CGFloat(self) * ratio
}
}
extension Int {
var adjusted: CGFloat {
let ratio: CGFloat = UIScreen.main.bounds.width / 375
let ratioH: CGFloat = UIScreen.main.bounds.height / 667
return ratio <= ratioH ? CGFloat(self) * ratio : CGFloat(self) * ratioH
}
var adjustedWidth: CGFloat {
let ratio: CGFloat = UIScreen.main.bounds.width / 375 …
```
=> Chore [#4] adjust extension 추가

YELLO-iOS/YELLO-iOS/Global/Extensions/UILabel+.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/AddFriendsView.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift
- `return` 키를 이용해서 입력을 완료할 수 있도록 코드를 추가했습니다. 
- 친구 추가뷰에서 선택된 친구 라벨 색상을 변경했습니다. 
- `return` 키 이용 입력 완료 
https://github.com/team-yello/YELLO-iOS/blob/98aed88bd1c5b2b88dda8e3953a47f45e57606ae/YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift#L86-L88
- 여러 개의 텍스트를 한 번에 색상을 변경할 수 있도록 extension 추가
https://github.com/team-yello/YELLO-iOS/blob/98aed88bd1c5b2b88dda8e3953a47f45e57606ae/YELLO-iOS/YELLO-iOS/Global/Extensions/UILabel%2B.swift#L39-L50
|친구 선택 뷰 | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-07-15 at 14 54 39](https://github.com/team-yello/YELLO-iOS/assets/68178395/bb304014-558f-4c9d-bbcf-7ce9f1cf238e) |
|키보드 return | ![Simulator Screen Recording - iPhone SE (3rd …
=> Fix [#52] keyboard 이용 return

YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Global/KeychainHandler.swift, YELLO-iOS/YELLO-iOS/Network/Base/HTTPHeaderFieldKey.swift, YELLO-iOS/YELLO-iOS/Network/Base/TargetType.swift, YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift, YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/DeleteUserRequestDTO.swift, YELLO-iOS/YELLO-iOS/Network/Profile/Router/ProfileTarget.swift, YELLO-iOS/YELLO-iOS/Network/Profile/Service/ProfileService.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/MyYelloDetailModel.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/ProfileSettingView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/ViewController/ProfileSettingViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift
- 계정 탈퇴 API를 연결했습니다. 
- 로그아웃 구현했습니다. 
- 계정 탈퇴 API 연결 후 다음과 같은 로직을 추가했습니다. 
> 카카오 로그인 연결 끊기
https://github.com/team-yello/YELLO-iOS/blob/23aac6056d5e6345bc01ccfd87204dc5c049b2eb/YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift#L99-L108
> `keyChain` 안의 정보 삭제
https://github.com/team-yello/YELLO-iOS/blob/23aac6056d5e6345bc01ccfd87204dc5c049b2eb/YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift#L109
> 회원 탈퇴 이후 `rootView` 변경
https://github.com/team-yello/YELLO-iOS/blob/23aac6056d5e6345bc01ccfd87204dc5c049b2eb/YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/Withdrawal/View/WithdrawalAlertView.swift#L110-L112
- 로그아웃 시 카카오 계정 로그아웃을 진행합니다. 
https://github.com/team-yello/YELLO-iOS/blob/96504b3d481edc759429029b4bf67065 …
=> Network [#87] 계정 탈퇴 API 연결, 로그아웃 구현

YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SignUpRequestDTO.swift, YELLO-iOS/YELLO-iOS/Network/Profile/DTO/Request/DeleteUserRequestDTO.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Cells/FriendsTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/User.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/AddFriendsViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/OnboardingEndViewController.swift
- 추가될 친구 목록을 싱글톤에 저장하고 API로 넘겨주었습니다. 
- 카카오 소셜 연결을 통해 카카오 친구를 받아오는 로직을 다음과 같이 구현했습니다. 
> 싱글톤에 `kakaoFriends`이라는 `String` 배열을 만들어서 저장했습니다. 
https://github.com/team-yello/YELLO-iOS/blob/8c5143497015270e21a70252fa50e5d9c159e06f/YELLO-iOS/YELLO-iOS/Presentation/Onboarding/User.swift#L23
> 카카오 소셜 연결을 통해 카카오 친구를 불러왔습니다. 
https://github.com/team-yello/YELLO-iOS/blob/8c5143497015270e21a70252fa50e5d9c159e06f/YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift#L31-L42
| 카카오톡 연결 화면 | ![Simulator_Screen_Recording_-_iPhone_SE__3rd_generation__-_2023-07-19_at_20_47_09_AdobeExpress (1)](https://github.com/team-yello/YELLO-iOS/assets/68178395/6c69253e-c205-4331-bbfa-f7f5123a6d64) |
|친구 추가된 …
=> Feat [#91] 친구 추가 API 연결 및 친구추가 로직 구현 

YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
- 무한 스크롤이 페이지마다 끊겨서 보여지는게 아니라 연속으로 한번에 되는 이슈를 해결했습니다.
- 비동기 처리 해주는 걸로 이슈 바로 해결..
https://github.com/team-yello/YELLO-iOS/blob/f769ce094982e0afa23beb3f6585f2fb7c22b889/YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift#L196-L199
- 없습니다.
| 화면종류 |  ![image](https://github.com/team-yello/YELLO-iOS/assets/109775321/946dc4fe-e107-463a-8844-e9b5cb9beefc) |
Resolved #102
=> Fix [#102] 무한 스크롤 연속으로 되는 이슈 해결

YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingLocked/VotingLockedViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- VotingStartViewController에서 viewWillAppear시 서버통신을 해서 친구 수가 4명 이상인지 다시 판단할 수 있도록 로직을 수정했습니다.
- Network Base의 APIRequestLoader파일을 아래와 같이 수정했습니다 ‼️
- StatusCode case를 200...299, 400...499로 수정했습니당!
https://github.com/team-yello/YELLO-iOS/blob/0892d13cbf5ad559a14955c922c80585e31081a9/YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift#L50-L57
Resolved #104
=> Fix [#104] 친구 수 4명 이하 로직 수정

YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Presentation/Base/BaseBottomSheetViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSearchViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/StudentInfoViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/StudentIdView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/BottomFriendProfileViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
- iOS 14에서 네비게이션바 커스텀이 되지 않고 바텀 시트를 지원하지 않아서 기기대응을 했습니다. 
- iOS 15 이하의 기기에는 다른 처리를 하도록 분기 처리를 했습니다.
- 바텀 시트를 커스텀 뷰로 만들어서 제작했습니다. 
| 온보딩 네비게이션바 커스텀 안됨 | ![Simulator Screenshot - iPhone6s - 2023-07-20 at 20 46 47](https://github.com/team-yello/YELLO-iOS/assets/68178395/58d5b2a7-7178-40bc-8c10-8a3b329f16c7) |
| 바텀시트 커스텀| ![Simulator Screenshot - iPhone6s - 2023-07-20 at 20 52 40](https://github.com/team-yello/YELLO-iOS/assets/68178395/6c7e762a-3346-474e-9e27-e47925b9366a)|
Resolved #101
=> Fix [101] iOS 15 이하 기기 대응 

YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/GetHintView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailNavigationBarView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/PointLackView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UsePointView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloNavigationBarView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/FriendCountView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift
- 포인트가 아주 많아졌을 때의 레이아웃을 재설정 했습니다. 9억 기준으로 맞췄습니다.. 10억이 넘지 않길 바랄뿐
- 내 프로필과 내 친구 부분 토탈 카운트 레이아웃 수정했습니다.
- 없슴둥 ㅋㅋ
|    내 프로필 토탈 카운트   |   내 옐로 토탈 카운트   | 내 옐로 포인트 사용 시 레이아웃 |
| :-------------: | :----------: | :----------: |
| ![IMG_1922](https://github.com/team-yello/YELLO-iOS/assets/109775321/9bc9eec5-1afc-45d6-b050-c09eace9d5c7) | ![IMG_1923](https://github.com/team-yello/YELLO-iOS/assets/109775321/4ea854f7-1a5c-4457-87aa-8fc2230a71d6) | ![ezgif-3-0ba0da09ba](https://github.com/team-yello/YELLO-iOS/assets/109775321/9508dc7d-d7a8-4d8e-abe9-4cc912c782f5) |
Resolved #109
=> Fix [#109] 포인트 레이아웃

YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift
- 투표화면 이름 BackGroundView 글자길이에 맞게 크기 대응
- 투표화면 키워드 BackGroundView 글자길이에 맞게 크기 대응
- 이제 이름, 키워드에 따라 BackgroundView의 길이가 잘 변합니당 ‼️
https://github.com/team-yello/YELLO-iOS/assets/97782228/bad41754-aded-45bc-88ba-e71c7313173c
Resolved #107
=> Fix [#107] 글자길이에 맞게 이름,키워드 BackgroundView 대응

YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloResponseDTO.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyFriendTableViewCell.swift
- 내 옐로 부분이 Indexpath 때문에 계속 터져서 diffable datasource로 변경하였습니다. 캡쳐하는 방식으로 바뀌는 정보들에 대해서 다시 불러오고 애니메이션도 좀 더 자연스럽고 UX적으로 좋아졌습니다!! 
- UITableViewDataSource랑 Delegate를 같이 쓰고 있어서 아직 데이터 흐름을 이해하지 못했는데 이 부분 다시 리팩토링 진행하도록 하겠습니다.. 지금 코드가 많이 더러운 상태입니다..
- 읽음 처리가 되는 걸 확인하지 못하고 있어서 다시 새로운 쪽지 들어왔을 때 상태 보고 다시 수정하겠습니다!
| 화면종류 | ![ezgif-4-5c5474b330](https://github.com/team-yello/YELLO-iOS/assets/109775321/a0ad1c32-f789-4068-a216-f12bb328db66) |
현재 화면에서는 읽음 처리가 꼬이는 상황입니다.. 이 부분 다시 확인하고 수정하겠습니다!
Resolved #124
=> Fix [#124] 내 옐로 앱 터지는 이슈 해결

YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
카카오 소셜 SDK 사용 중 친구 목록을 10개만 불러오도록 제한되어 있던 부분을 100개로 증가했습니다.
- SDK 내부를 보면 다음과 같습니다. 
``` swift
public func friends(offset: Int? = nil,
limit: Int? = nil,
order: Order? = nil,
friendOrder: FriendOrder? = nil,
completion:@escaping (Friends<Friend>?, Error?) -> Void) {
```
`limit`파라미터를 이용해서 카카오톡 친구를 최대 몇명을 불러올지 설정해줍니다. 하지만 기존 코드에는 그 부분을 변경하는 파라미터가 누락되어 `limit`가 자동으로 10으로 설정되었습니다. 다음과 같이 변경했습니다. 
```swift
TalkApi.shared.friends(limit: 100) {(friends, error) in
if let error = error {
print(error)
} else {
// do something
}
``` 
- 7월 31일 서버와 논의 후 카카오 친구 불러오기 부분은 한 페이지당 개체 수가 100으로 변경되어 limit를 100으로 변경했습니다. 
| 추천친구뷰, 온보딩 친구 추가 뷰 | ![image](https://github.com/team-yello/YELLO-iOS/assets/68178395/b06df711-f28d-4804-94cf-2d6e952bbcab) | …
=> Fix [#135] 카카오톡 친구 제한 해제

YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift
- id입력 텍스트필드에 글자수 제한을 해두었습니다. 
- 제한된 글자수 (20자)가 넘어가면 더 이상 입력이 되지 않고 자동으로 키보드를 내립니다. 
- `UITextFieldDelegate`를 이용하여 글자수 제한이 넘어가면 더 이상 입력이 되지 않도록 제한했습니다. 
``` swift 
func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
guard let text = textField.text else {return false}
// 최대 글자수 이상을 입력한 이후에는 중간에 다른 글자를 추가할 수 없게끔 작동
if text.count >= maxLength && range.length == 0 && range.location < maxLength {
return false
}
return true
}
```
- `Notificationcenter`를 이용하여 20자 이상의 글자는 제거되고 글자수 제한이 넘으면 자동으로 키보드를 내리도록 했습니다. 
``` swift
if text.count > maxLength {
textField.resignFirstResponder()
}
```
| ID 작성 |![Simulator Screen Recording - iPhone 13 mini - 2023-07-31 at 00 23 …
=> [Fix] ID 글자수 제한 

YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift
⬇️ 로컬 푸시 알림 구현
- AppDelegate
https://github.com/team-yello/YELLO-iOS/blob/8f80169ee37dd0277f6bf8f9aa23966c471dda41/YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift#L16-L20
https://github.com/team-yello/YELLO-iOS/blob/8f80169ee37dd0277f6bf8f9aa23966c471dda41/YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift#L46-L62
- 알림받기 뷰가 구현되지 않아서 우선 VotingStartViewController에 들어왔을 때 알림 권한 요청을 하도록 구현했습니다.
https://github.com/team-yello/YELLO-iOS/blob/8f80169ee37dd0277f6bf8f9aa23966c471dda41/YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingStart/VotingStartViewController.swift#L192-L199
- 타이머 시간이 다 되면 푸시알림이 옵니다.
https://github.com/team-yello/YELLO-iOS/blob/8f80169ee37dd0277f6bf8f9aa23966c471dda41/YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingTimer/VotingTimerViewController.swift#L25-L30
|    구현 내용    | …
=> Feat [#137] 로컬 푸시 알림 구현

YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloDetailResponseDTO.swift, YELLO-iOS/YELLO-iOS/Network/MyYello/DTO/Response/MyYelloResponseDTO.swift, YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Button/MyYelloButton.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloOnlyNameTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/UseTicketView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/ViewController/MyYelloDetailViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/View/MyYelloListView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/ViewController/MyYelloViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/SchoolFriendView.swift
- API 연결에 따라 내 옐로에서 구독 여부와 열람권 유무에 따른 UI를 변경했습니다.
- 없습니다..아마도
|    키워드 -> 초성 -> 이름    |   키워드 -> 이름   |   이름 -> 키워드   |
| :-------------: | :----------: | :----------: |
| ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-08-18 at 22 41 02](https://github.com/team-yello/YELLO-iOS/assets/109775321/84eb4dbe-2cb0-4f61-a35d-32874e16a50a)  | ![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-08-18 at 22 41 15](https://github.com/team-yello/YELLO-iOS/assets/109775321/7bc0fac6-84b7-4039-828f-6bf5380d2431)  |![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-08-18 at 22 52 13](https://github.com/team-yello/YELLO-iOS/assets/109775321/a208074c-86d4-4747-a60e-ac279b052d7f)  |
Resolved #205
=> Feat [#205] 내 옐로 구독, 열람권 여부에 따른 UI 변경

YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift, YELLO-iOS/YELLO-iOS/Global/Shared/AppStoreCheck.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloDefaultTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloKeywordTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloNameTableViewCell.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Cells/MyYelloOnlyNameTableViewCell.swift
- [Major].[Minor].[Patch] 버전 중 Major나 Minor가 달라질 경우 모든 화면에서 강제 업데이트를 하도록 설정해주었습니다.
- https://github.com/team-yello/YELLO-iOS/blob/64ab262285bea0f3cab9e68f1a2b2a0eb2b8aeff/YELLO-iOS/YELLO-iOS/Global/Shared/AppStoreCheck.swift#L12-L13
버젼 정보를 받아오도록 했습니다.
- https://github.com/team-yello/YELLO-iOS/blob/64ab262285bea0f3cab9e68f1a2b2a0eb2b8aeff/YELLO-iOS/YELLO-iOS/Global/Shared/AppStoreCheck.swift#L18-L29
앱스토어의 버전을 받아오는 함수입니다. 
- https://github.com/team-yello/YELLO-iOS/blob/64ab262285bea0f3cab9e68f1a2b2a0eb2b8aeff/YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift#L212-L229
Major나 Minor가 다른 경우 알럿이 띄워지도록 했습니다. 
- https://github.com/team-yello/YELLO-iOS/blob/64ab262285bea0f3cab9e68f1a2b2a0eb2b8aeff/YELLO-iOS/YELLO-iOS/Application/SceneDelegate.swift#L196-L200
백그라운드에서 포그라운드로 진입시에도 해당 함수가 실행되며 …
=> Feat [#212] 앱스토어 강제 업데이트 설정

YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailView.swift
- 푸시 알림에서 내 옐로 상세보기로 들어갈 경우 indexNumber의 기본값이 0이어서 첫번째 키워드가 보여지는 문제를 해결하였습니다. 기본값을 -1로 설정하였고, -1일 경우에는 키워드, 초성, 이름이 모두 보여지지 않도록 설정했습니다. 
- 안드와 협의한 사항.. 푸시를 선택하고 리스트로 돌아갔을 때 반영이 되지 않아있습니다. 기술적으로 구현하기 어려운 부분이었기에 내일 QA 진행 후 협의하여 결정하도록 하겠습니다. 
| 화면종류 | 없음 |
Resolved #216
=> Fix [#216] 내 옐로 오류 수정

YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Application/AppDelegate.swift, YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/DeviceTokenRefreshRequestDTO.swift, YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/MajorSearchRequestQueryDTO.swift, YELLO-iOS/YELLO-iOS/Network/Onboarding/DTO/Request/SchoolSearchRequestQueryDTO.swift, YELLO-iOS/YELLO-iOS/Network/Onboarding/Router/OnboardingTarget.swift, YELLO-iOS/YELLO-iOS/Network/Onboarding/Service/OnboardingService.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift
서버 변경 사항을 적용했습니다. 
- 학교 검색 라우터 변경
- 학과 / 학교 검색 쿼리 DTO 수정
- 디바이스 토큰 재발급 서버 부착
- **현 상황**: 디바이스 토큰이 앱이 켜질 때마다 발급 -> 재발급 네트워크 통신 -> 존재하는 디바이스 토큰이므로 409 에러 발생 
- **매번 이걸 Put 해주는 게 맞는지에 대한 고민이 조금 더 필요한 것 같습니다.** FCM 토큰은 따로 재발급 주기가 없어서 아래 상황이 아니면 재발급이 되지 않습니다. 하지만 아래 상황을 감지할 방법이 정확히 존재하지 않아서 일단 가져올 때마다 디바이스 토큰 재발급 로직을 구현해뒀습니다. 
```
FCM 토큰이 재발급 되는 상황
- 앱이 인스턴스 ID를 삭제한 경우
- 앱이 새 기기에서 복원되었을 경우
- 사용자가 앱을 제거/ 재설치한 경우
- 사용자가 앱 데이터를 지운 경우 
```
| 화면종류 | 없습니다 |
Resolved #230
=> Fix [#230] 온보딩/디바이스 토큰 서버 변동 사항 적용

YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Tutorial/ViewController/TutorialViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/VotingPoint/VotingPointViewController.swift
- 로그아웃 하고 다시 로그인할 때 옐로하기 부분이 깜빡이는 이슈를 해결하였습니다.
- 탈퇴하고 다시 로그인할 때 옐로하기 부분이 깜빡이는 이슈를 해결하였습니다.
- 수정한 부분 주석 달아놓았습니다.
로그아웃 했다가 재로그인, 탈퇴했다가 재로그인시 옐로하기 부분이 깜빡이는 이슈 해결
https://github.com/team-yello/YELLO-iOS/assets/97782228/87c24c97-53e8-40cd-9fe3-f91503c80151
Resolved #235
=> Fix [#235] 외부 QA 사항 반영

YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift
카카오 친구 연결뷰 분기 처리 진행
카카오톡 로그인 시 카카오 친구 연결을 하면 `카카오 친구 연결뷰`의 카카오연결에서 외부 링크로 이동하지 않기 때문에 불필요한 뎁스가 생겼습니다. 이 부분을 개선하기 위해 동의 여부로 분기처리를 진행했습니다.
또한 카카오톡이 없는 카카오계정으로 로그인 시 카카오 친구 연결이 되지않도록 처리했습니다. 
|친구를 카카오톡 로그인에서 동의하지 않은 상태 |![Simulator Screen Recording - iPhone 14 Pro - 2023-09-19 at 01 58 30](https://github.com/team-yello/YELLO-iOS/assets/68178395/6bafe191-6702-4528-8424-73f12ead33d3) |
|카카오톡 로그인 시 동의한 상태|![Simulator Screen Recording - iPhone 14 Pro - 2023-09-19 at 02 29 53](https://github.com/team-yello/YELLO-iOS/assets/68178395/bcddb787-601f-4952-9c42-5476157c821e)|
|카카오계정(카카오톡 존재X)으로 로그인|![Simulator Screen Recording - iPhone 14 Pro - 2023-09-19 at 02 32 01](https://github.com/team-yello/YELLO-iOS/assets/68178395/6162d3a3-1046-4e8d- …
=> Fix [#253] 카카오싱크 로직 변경

YELLO-iOS/YELLO-iOS/Network/Purchase/Service/IAPService.swift, YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
- transactionID를 자체 서버 측으로 보내주는 과정에서 무작위로 중복되어 보내지는 경우가 있어 500 에러가 떴는데 해당 부분 정확한 원인을 찾지 못했기 때문에 우선적으로 결제 되는 과정에서 결제 완료 처리된 transactionID가 있는지 유무를 나눠서 분기처리 했습니다. 추후 원인 발견하게 된다면 수정토록 하겠습니다!
- x
| 화면종류 | x |
Resolved #258
=> Fix [#258] 결제 중복 500 에러 해결

YELLO-iOS/YELLO-iOS/Global/Literals/String.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoConnectViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSelectViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoConnectView.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/View/KakaoLoginView.swift
- 학반 범위를 20반까지 확대했습니다. 
- 카카오 친구 연결 뷰와 카카오톡 로그인 부분에 '개인정보처리방침'버튼을 추가했습니다. 
- 없습니다.
| 카카오로그인 | ![Simulator Screen Recording - iPhone 14 Pro - 2023-10-03 at 15 23 09](https://github.com/team-yello/YELLO-iOS/assets/68178395/1d2ac521-d539-4bb6-baeb-4a618db18571) |
|고등학교 반 범위|![Simulator Screen Recording - iPhone 14 Pro - 2023-10-03 at 15 23 33](https://github.com/team-yello/YELLO-iOS/assets/68178395/f98b91da-64a0-4cd5-9bb9-e4644495b1db)|
Resolved #263
=> Feat [#263] 온보딩 수정 사항 반영

YELLO-iOS/YELLO-iOS/Global/Literals/String.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloSelectButton.swift
중학생 추가로 인한 라이팅을 변경했습니다. 
고등학생 -> 중/고등학생
| 온보딩 | ![RPReplay_Final1701960550](https://github.com/team-yello/YELLO-iOS/assets/68178395/947db2c0-3997-4578-ad27-a3da8d3f705d) |
Resolved #280
=> Fix [#280] 중학생 추가 라이팅 변경

YELLO-iOS/YELLO-iOS/Global/Shared/UserManager.swift, YELLO-iOS/YELLO-iOS/Network/Base/YelloRequestInterceptor.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
회원가입 시 카카오에서 정상적으로 넘어오지 않는 경우 기본 값을 넣도록 처리했습니다. 
- Firebase의 Crashlytics에서 비정상 종료가 아니더라도 로그를 보낼 수 있는 코드를 작성했습니다. 
``` swift
case .requestErr(let data):
self.isFail = true
self.view.showToast(message: "오류가 발생했습니다. 잠시후 다시 시도해주세요.")
Crashlytics.crashlytics().setUserID(UserManager.shared.yelloId)
Crashlytics.crashlytics().log("dto: \(requestDTO) \n message: \(data.message)")
return
```
| 로그인 에러 해결 | 없습니다 |
Resolved #287
=> Fix [#287] 회원가입 오류 HotFix

YELLO-iOS/YELLO-iOS/Network/Purchase/DTO/Response/PurchaseSubscibeNeedResponseDTO.swift, YELLO-iOS/YELLO-iOS/Network/Purchase/Router/PurchaseTarget.swift, YELLO-iOS/YELLO-iOS/Presentation/Subscription/SubscriptionExtensionView.swift, YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingFunction.swift, YELLO-iOS/YELLO-iOS/Presentation/Voting/Voting/VotingViewController.swift
- 투표하기 중 다음화면으로 넘어갈 때 검정색 배경들이 옆으로 밀리는 것과 같은 애니메이션을 추가했습니다.
- 재구독뷰 관련 서버 URL이 변경됨에 따라 Response DTO와 뷰 구현 부분을 수정했습니다.
- X
| 투표애니메이션 | ![Simulator Screen Recording - iPhone 15 - 2024-01-25 at 02 55 44](https://github.com/team-yello/YELLO-iOS/assets/97782228/cdb66f64-7b02-4072-a44b-369acf28aadc) |
Resolved #292
=> Feat [#292] 투표 애니메이션 추가 및 재구독뷰 서버 재연결

YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift
전달 받은 버튼 UI를 변경했습니다. 
- 없습니다!
| 14pro | ![IMG_9573](https://github.com/team-yello/YELLO-iOS/assets/68178395/548000db-099a-4fe5-bbbf-e082dc2a6a85) |
| SE | ![image](https://github.com/team-yello/YELLO-iOS/assets/68178395/53351944-faef-4f64-87bb-e0c0698c4fda) |
Resolved #290
=> Style [#290] 건너뛰기 버튼 UI 변경

YELLO-iOS/YELLO-iOS/Global/Literals/String.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/OnboardingViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditProfileHeaderView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/InfoView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/ViewController/ProfileViewController.swift
공지사항 서버 통신 후 `isAvailable` 값이 `true`인 경우 프로필 배너를 구현했습니다.
- `isAvailable` 값에 따라 헤더 높이 값이 변하기 때문에 아래와 같이 처리했습니다. 
``` swift
func tableView(_ tableView: UITableView, estimatedHeightForHeaderInSection section: Int) -> CGFloat {
return isAvailable ? 347.adjusted : 307.adjusted
}
```
- 마찬가지로, 공지가 없을 때 다시 레이아웃을 잡아야 하기 때문에 remake 함수를 사용했습니다. 
``` swift 
func updateNotification() {
self.notificationImageView.isHidden = !isAvailable
height = isAvailable ? 57.adjustedHeight : 0
notificationImageView.snp.remakeConstraints {
$0.height.equalTo(height)
$0.leading.trailing.equalToSuperview()
$0.top.equalTo(shopBackgroundView.snp.bottom).offset(10.adjusted)
$0.bottom.equalToSuperview()
}
}
```
| 공지가 있을 때 | ![Simulator Screen Recording - iPhone …
=> Feat [#319] 프로필 공지 배너 구현

YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Global/Literals/String.swift, YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift, YELLO-iOS/YELLO-iOS/Presentation/Base/BaseIconButton.swift, YELLO-iOS/YELLO-iOS/Presentation/Inviting/CloseButton.swift, YELLO-iOS/YELLO-iOS/Presentation/Inviting/InvitingView.swift, YELLO-iOS/YELLO-iOS/Presentation/MyYello/Detail/View/MyYelloDetailNavigationBarView.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloNavigationBarView.swift, YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentNavigationBarView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/InfoView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/MyProfileHeaderView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Main/View/ProfileView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Setting/View/SettingNavigationBarView.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/EmptyFriendView.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/RecommendingNavigationBarView.swift
- 3차 스프린트 1차 QA 변경 사항을 적용했습니다.
- 전반적인 backButton 터치 영역을 늘렸습니다.
- 라이팅 변경 적용 안된 것들 적용했습니다
- 내 프로필에서 생기는 검은선 삭제했습니다. header와 cell 사이의 구분선을 가려주기 위해서 얹었던 CALayer가 reload 될 때마다 그려지게 되는 점을 없애기 위해 remove 후 다시 add 할 수 있도록 했습니다. 
- x
|  내 프로필 검은 줄 삭제 및 기본 사진 변경  |  ![IMG_5919](https://github.com/team-yello/YELLO-iOS/assets/109775321/b6b56587-c4c3-4d49-9274-7c3713de33b3) |
|  검색 placeholder 라이팅 변경 | ![IMG_5921](https://github.com/team-yello/YELLO-iOS/assets/109775321/031707df-8f9a-4c65-bf4d-00a628478912) |
|   친구 초대 뷰 라이팅 변경  | ![IMG_5920](https://github.com/team-yello/YELLO-iOS/assets/109775321/e25f664e-ad61-4111-adfa-2ed6d7d2ae2d) |
Resolved #328
=> Fix [#328] 3차 스프린트 - 1차 QA 변경 사항 적용

YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Global/Extensions/Array+.swift, YELLO-iOS/YELLO-iOS/Global/Literals/String.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindMajorViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Modal/FindSchoolViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/SchoolSelectViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UniversityViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
`SearchBaseViewController`에서 지속적으로 발생하는 `Index out of range` 에러를 방지하도록 로직을 변경했습니다. 
검색 기능을 가진 뷰에 대한 전체적인 수정을 진행했습니다. 
- 검색하는 경우 검색결과를 담은 배열에 데이터가 반영되는 속도에 따라 간헐적으로 index 에러가 발생했습니다. 이를 해결하기 위해 SafeArrayExtension을 추가하여 index를 optional 값으로 받아서 fatal Error가 발생하는 것을 방지했습니다. 
https://github.com/team-yello/YELLO-iOS/blob/c8fcde71d160927072d54990ca98171dda10f0f8/YELLO-iOS/YELLO-iOS/Global/Extensions/Array%2B.swift#L10-L20
https://github.com/team-yello/YELLO-iOS/blob/c8fcde71d160927072d54990ca98171dda10f0f8/YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/Base/SearchBaseViewController.swift#L97-L108
- 검색기능 뷰 전체적으로 코드 정리 / 로직 정리와 네이밍 변경이 있었습니다. 
- 기존에 bool값을 이용해서 분기처리했던 고등학생/대학생 구분을 GroupType을 사용하여 분기처리했습니다. 
https://github.com/team-yello/YELLO-iOS/blob/c8fcde71d160927072d54990ca98171dda1 …
=> Fix [#324] 학교/학과 검색 index 이슈 해결

YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift
구독 상태가 아닐 때 "이미 구독 중인 상품" 알럿이 뜨는 오류를 해결했습니다. 
구독 상태가 소문자로 옴에 따라 `NORMAL`-> `normal`로 변경했습니다. 
| 화면종류 | 없습니다 |
Resolved #350
=> Fix  [#350] 구독 정보 오류 해결

YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/HighSchoolViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/Views/Helper/YelloSelectButton.swift, YELLO-iOS/YELLO-iOS/Presentation/Payment/View/PaymentView.swift, YELLO-iOS/YELLO-iOS/Presentation/Payment/ViewController/PaymentPlusViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Recommending/View/KakaoFriendView.swift
발견/해결한 오류는 다음과 같습니다. 
- `추천친구 > 카톡 친구들`에서 카카오톡 친구가 불러와지지 않는 오류 
- `상점뷰 `상단의 pageControl 오류 해결
- `온보딩` 학교 -> 반 -> 학년 선택 시 버튼 enable 되지 않는 오류 
카카오톡 친구가 불러와지지 않는 오류는 다음과 같은 오류 메시지를 표시했습니다. 
```
[‼️][Api.swift 151:29] -> response: api error: ClientFailed(reason: KakaoSDKCommon.ClientFailureReason.TokenNotFound, errorMessage: Optional("authentication tokens not exist."))
```
[공식 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/trouble-shooting#oidc)에 따르면 카카오 토큰이 존재하지 않아 발생하는 문제입니다. 이 경우에는 재로그인 시 정상 작동하기 때문에 다시 로그인을 진행해야합니다. 
문제 발생 원인은 사용자가 카카오의 리프레쉬 토큰이 만료되는 시점까지 접속한 기록이 없을 시 토큰이 아예 유효하지 않기 때문입니다. 이 문제를 방지하기 위해서 카카오톡 친구를 불러올 때, 카카오 accessToken의 유효성을 검사하고 토큰이 없을 경우 안내 토스트 메시지를 띄우도록 처리했습니다. 토큰 확인 로직은 [여기](https://developers.kakao.com/docs/latest/ko/kakaologin/ios#token-presence) …
=> Fix [#352] 출시 이후 발견한 오류 해결

YELLO-iOS/YELLO-iOS.xcodeproj/project.pbxproj, YELLO-iOS/YELLO-iOS/Global/Literals/String.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/UserInfoViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/View/EditCheckView.swift, YELLO-iOS/YELLO-iOS/Presentation/Profile/Edit/ViewController/EditSchoolInfoViewController.swift
- 프로필 변경 시 확인하는 팝업을 추가했습니다. 
- 논의된 변경 사항을 적용했습니댜.
- 온보딩 아이디 중복 확인에서 빈 문자를 보냈을 때 true 값이 들어옵니다. 이로 인해 "이미 존재하는 아이디입니다." 라이팅이 적용된 것을 확인했습니다. 수정을 위해 초기 상태로 만드는 함수 `setInitialState()`를 만들어서 중복성 검사 전 빈 문자열인 경우 초기 상태를 유지하도록 구현했습니다. 
```swift
private func setInitialStyle() {
baseView.idTextField.helperLabel.setLabelStyle(text: StringLiterals.Onboarding.Id.idHelper, State: .id)
baseView.idTextField.textField.setButtonState(state: .id)
nextButton.setButtonEnable(state: false)
}
func textFieldDidEndEditing(_ textField: UITextField) {
if textField == baseView.idTextField.textField {
guard let idText = textField.text else { return }
if idText.isEmpty {
setInitialStyle()
return
}
self.checkDuplicate(id: idText)
}
self.checkButtonEnable()
}
```
| :-------------: | …
=> Feat [#355] 프로필 변경 확인 팝업 및 수정 사항 적용

YELLO-iOS/YELLO-iOS/Global/Literals/String.swift, YELLO-iOS/YELLO-iOS/Presentation/Around/View/AroundView.swift, YELLO-iOS/YELLO-iOS/Presentation/Notification/NotificationView.swift, YELLO-iOS/YELLO-iOS/Presentation/TabBar/YELLOTabBarController.swift
- 유저대상 공지 다시 보지 않기 -> 오늘 하루 보지 않기 로 변경
- UserDefaults에 Date 타입의 object를 추가하여 오늘 날짜와 비교하는 함수로 하루가 지났는지 지나지 않았는지를 판단합니다.
| 화면종류 | X |
Resolved #360
=> Feat [#360] 3차 스프린트 건의사항 반영

YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/KakaoLoginViewController.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
온보딩 오류 발생 시 카카오 로그인으로 이동하는 플로우를 추가했습니다. 
- 기존에 로그인 버튼은 한 번 누르면 비활성화되어 취소 후 다시 돌아왔을 때 동작하지 않음을 확인했습니다. 이를 해결하기 위해 로그인이 되지 않았으면 버튼을 활성화하는 로직을 추가했습니다. 
- 회원가입 서버통신 실패로 로그인 화면으로 돌아온 경우, 삭제 후 다시 들어온 것과 마찬가지로 푸시 알림 설정과 튜토리얼으로 돌아가도록 구현했습니다. 
| 로그인 로직 | ![Simulator Screen Recording - iPhone 15 Pro - 2024-04-12 at 00 20 41](https://github.com/team-yello/YELLO-iOS/assets/68178395/fa834913-9386-4d31-8b7a-39dfb65c4732) |
Resolved #371
=> Fix [#371] 회원가입 오류 대응

YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift, YELLO-iOS/YELLO-iOS/Network/Base/NetworkResult.swift, YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift
오류 원인 파악을 위한 토스트 메시지 내용 변경
- 토스트 메시지 위치 확인 부탁드립니다 ~ 버튼 위로 올라오도록 설정해뒀어요! (기존 위치 : 버튼 아래)
- 기존 400대 에러도 isVaild로 decoding 과정을 거쳤었는데, 403, 401을 제외한 400대 에러와 500에러는 status code를 포함한 Result로 반환하도록 수정했습니다. 사이드이펙트 없는지 테스트 완료했으나, 각자 맡은 부분에 에러 처리 있는지 확인 부탁드립니다!
https://github.com/team-yello/YELLO-iOS/blob/a2520c91f2130dd85fa7b8df8ba82774d298b85c/YELLO-iOS/YELLO-iOS/Network/Base/APIRequestLoader.swift#L56-L64
- 기존에 발생하는 문제(500 에러 발생 시 재로그인 시도 하면 로그인되는 현상)가 아직 해결되지 않아 500에러 발생 시 다시 소셜 로그인 화면으로 돌아가는 로직은 포함시켜두었습니다.
https://github.com/team-yello/YELLO-iOS/blob/a2520c91f2130dd85fa7b8df8ba82774d298b85c/YELLO-iOS/YELLO-iOS/Presentation/Onboarding/ViewController/RecommendIdViewController.swift#L172-L179
| SE | <img src= …
=> Fix [#375] 추천인 코드 오류 시 토스트 메시지 변경
